faceapp/urls.py
from django.urls import path

from . import views
app_name = 'faceapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('save', views.save_video, name='save'),
    path('delete', views.delete_video, name='delete'),
]

facevideo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('faceapp/', include('faceapp.urls')),
]

faceapp/models.py
from django.db import models

# Create your models here.

class Video(models.Model):
    user_id = models.CharField('user id',max_length=20)
    pub_date = models.DateField('date of video')
    video_path = models.CharField('video file path', max_length=255, default="")

faceapp/views.py
from django.core.exceptions import ViewDoesNotExist
from django.http import HttpResponse, request
from django.shortcuts import get_object_or_404, render
from .models import Video
from datetime import datetime
from django.conf import settings
import time


def index(request):
    videos = Video.objects.filter(user_id='sajjan')
    return render(request,'index.html',{'videos': videos})

def get_videos(request,user_id):
    videos = Video.objects.filter(user_id='sajjan')
    return render(request,'index.html',{'videos': videos})

def save_video(request):
    user_id = request.POST['user_id']
    path = settings.STATIC_URL+"/"+user_id+str(time.time())+".webm"
    video = Video(user_id=user_id,pub_date=datetime.today().strftime('%Y-%m-%d'),video_path=path)
    video.save()
    print(request.FILES)
    uploaded_file = request.FILES['video_file']
    with open(path,'wb+') as dest:
        for chunk in uploaded_file.chunks():
            dest.write(chunk)
    videos = Video.objects.filter(user_id=user_id)
    return render(request,'index.html',{'videos': videos})

def delete_video(request):
    videos = Video.objects.filter(user_id="sajjan")
    videos.delete()
    videos = Video.objects.filter(user_id='sajjan')
    return render(request,'index.html',{'videos': videos})

faceapp/templates/index.html
<html>

<body>
    <video id="player" controls></video>
    <button id="start_stop">stop </button>
    <button id="save">save </button>
    <a id="download">Download</a>
    <h2> My Videos</h2>
    <video id="recorded" controls></video>
    <form action="{% url 'faceapp:save' %}" method="post" enctype="multipart/form-data" id="video-form" >
        {% csrf_token %}
        <input type="hidden" id="videoid" name="video" value="3487">
        <input type="hidden" id="user_id" name="user_id" value="sajjan">
        <input type= "file" id="video_file" name="video_file">
    </form>
    {% for video in videos %}
    <h3> {{ video.pub_date }} </h3>
     <video id="recorded" src="{{ video.video_data }}" type="video/webm" src="{{video.video_path }}" controls></video>
    {% endfor %}
    <script>
        let shouldStop = false;
        let stopped = false;
        const downloadLink = document.getElementById('download');
        const stopButton = document.getElementById('start_stop');
        const savebutton = document.getElementById('save');
        var video_file = document.getElementById("video-form").elements["video_file"]
        var player = document.getElementById('player');
        var recorded = document.getElementById('recorded');
        var video_data = document.getElementById("video-form").elements["video"];

        stopButton.onclick =  function () {
            shouldStop = true;
        }

        savebutton.onclick = function(){
            document.getElementById("video-form").submit()
        }
        
        var handleSuccess = function (stream) {
            player.srcObject = stream;
            const options = { mimeType: 'video/webm' };
            const recordedChunks = [];
            const mediaRecorder = new MediaRecorder(stream, options);

            mediaRecorder.ondataavailable  =  function (e) {
                if (e.data.size > 0) {
                    recordedChunks.push(e.data);
                }

                if (shouldStop === true && stopped === false) {
                    mediaRecorder.stop();
                    stopped = true;
                }
            }

            mediaRecorder.onstop = function () {
                downloadLink.href = URL.createObjectURL(new Blob(recordedChunks));
                downloadLink.download = 'acetest.webm';
                var blob = new Blob(recordedChunks,{type: 'video/webm'});
                video_data.value = blob;
                var url = URL.createObjectURL(blob);
                recorded.src = url;
                video_file.value = url
            }

            mediaRecorder.start(5000);
        };

        navigator.mediaDevices.getUserMedia({ audio: true, video: true })
            .then(handleSuccess);

    </script>
</body>

</html>